config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, skip: :registrations, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider', to: "omniauth_callbacks#%{provider}", as: :user_omniauth_authorize

    resource :registration,
      only: [:new, :create, :edit, :update, :edit_payment_settings],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'registrations',
      as: :user_registration do
        get :cancel
        get "/payment/edit", as: :edit_payment_settings, to: "registrations#edit_payment_settings"
        get "/twitter_redirect", as: :twitter_redirect, to: "registrations#twitter_redirect"
      end
  end

  root to: "proposals#index"

  resources :users, only: [:index, :destroy] do
    get :watchers
    get :watching
    put :follow
    put :unfollow

    put :impersonate

    resources :characters, controller: "users/characters"
    resources :questions, controller: "users/questions", only: [:create, :update]
    resources :reports, controller: "users/reports", only: [:create]
    resources :wishes, controller: "users/wishes", only: [:create, :destroy]
    resource :profile, controller: "users/profiles", only: [:edit, :update]
    resources :assets, controller: "users/assets", only: [:index, :create, :update, :destroy]
    resources :musics, controller: "users/musics", only: [:create, :update, :destroy]
    get "/pictures", to: "users/assets#index"
  end

  resources :artists, only: [] do
    resources :proposals, only: [:new, :create, :edit, :update, :destroy], controller: "artists/proposals" do
      get :duplicate
    end

    resources :quotations, only: [:new, :create, :index, :edit, :update, :destroy], controller: "artists/quotations" do
      put :publish
      put :unpublish
    end
  end

  resources :commissioners, only: [] do
    resources :quotations, only: [:index], controller: "commissioners/quotations" do
      put :publish
      put :unpublish
    end
  end

  resources :proposals, only: [:index, :show] do
    resources :quotations, only: [:new, :create, :edit, :update, :destroy], controller: "proposals/quotations"

    put :activate
    put :deactivate
  end

  resources :quotations, only: [:show] do
    put :accept
    put :refuse
    put :cancel_approval
    put :cancel_refusal
    put :paid
    put :finish

    put :rate_commissioner
    put :rate_artist

    resources :invoices, controller: "quotations/invoices" do
      put :paid
      put :cancel_paid

      get :paypal_redirect
    end
  end

  resources :quotation_comments, only: [:create]
  resources :characters, only: [:show] do
    put :activate
    put :deactivate
  end

  resources :messages, only: [:index, :create]

  resources :feedbacks, only: [:create]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index, :show] do
    resource :comments, only: [:create], controller: "announcements/comments"
  end

  put "notifications/mark_all_as_read", to: "notifications#mark_all_as_read"

  get "/opensearch.xml" => "proposals#opensearch", as: "opensearch"

  get "/:user_id" => "users/profiles#show", as: "profile"

  get '/s3/sign', to: "s3#sign"

  # legacy
  get "/users/:user_id/profile", to: redirect('/%{user_id}')
  get "/:user_id/characters", to: redirect('/%{user_id}')
  get "/artists/:user_id/proposals", to: redirect('/%{user_id}')
end

app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  author     :string
#  body       :text
#  created_at :datetime         not null
#  draft      :boolean          default(TRUE)
#  id         :integer          not null, primary key
#  slug       :string
#  title      :string
#  updated_at :datetime         not null
#

class Announcement < ApplicationRecord
  extend FriendlyId
  
  has_many :comments, class_name: "AnnouncementComment"

  friendly_id :slug_candidates, use: [:slugged, :finders, :history]

  protected

  def slug_candidates
    [ [:title] ]
  end
end

app/controllers/announcements/comments_controller.rb
class Announcements::CommentsController < ApplicationController
  def create
    @comment = AnnouncementComment.new(strong_params(AnnouncementComment.new))

    authorize @comment

    @comment.save
    redirect_to announcement_url(@comment.announcement, anchor: "comments")
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  def index
    @announcements = Announcement.where(draft: false).order(created_at: :desc).page(page).per(per)
  end

  def show
    @announcement = Announcement.find(params[:id])
    authorize @announcement

    @comments = @announcement.comments.order(created_at: :desc)
  end
end

app/helpers/announcements/comments_helper.rb
module Announcements::CommentsHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcement.html.haml
.col.s12.l10.offset-l1
  .card.announcement
    .card-content
      = render partial: "announcements/text", locals: { announcement: announcement }
    .card-action.right-align
      = link_to t(".comments", { count: announcement.comments.count }), announcement_path(announcement, anchor: "comments"), class: 'blue-text'

app/views/announcements/_text.html.haml
.text
  .row
    .col.s12
      %h1= announcement.title
      .flow-text
        = raw render_markdown(announcement.body)
  .right-align
    %strong= announcement.author

app/views/announcements/index.html.haml
.container
  .row
    = render partial: "announcements/announcement", collection: @announcements, cache: Proc.new { |announcement| [announcement] }
    = paginate @announcements

app/views/announcements/show.html.haml
= cache [@announcement, current_user] do
  .container
    .row
      .col.s12.l10.offset-l1
        .card.announcement
          .card-content
            .row
              .col.s12
                = render partial: "announcements/text", locals: { announcement: @announcement }
            %ul.collection.comments#comments
              - if current_user.present?
                %li.collection-item
                  .row
                    .col.m2.center-align.hide-on-small-only
                      %img.responsive-img.circle{:alt => "", :src => "#{current_user.profile.avatar_url(:avatar)}"}
                      %br
                    .col.s12.m10
                      = form_for(AnnouncementComment.new, url: announcement_comments_path(announcement_id: @announcement.id), method: :post) do |f|
                        = f.hidden_field 'announcement_id', value: @announcement.id
                        = f.hidden_field 'sender_id', value: current_user.id
                        = f.text_area 'body', class: "materialize-textarea", placeholder: t('.send_comment')
                        .right-align
                          = f.button class: 'waves-effect waves-light btn-flat' do
                            = t('.submit_comment')
              - @comments.each do |comment|
                %li.collection-item.conversation
                  .row.row-no-bottom-margin
                    .col.s3.m2.center-align
                      = link_to profile_path(comment.sender) do
                        %img.responsive-img.circle{:src => "#{comment.sender.profile.avatar_url(:avatar)}"}
                      %br/
                      %span.ago= t(".ago", { time: time_ago_in_words(comment.created_at) })
                    .col.s9.m10
                      %h5
                        = link_to comment.sender.name, profile_path(comment.sender)
                      %p
                        = format_text(comment.body)