config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, skip: :registrations, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider', to: "omniauth_callbacks#%{provider}", as: :user_omniauth_authorize

    resource :registration,
      only: [:new, :create, :edit, :update, :edit_payment_settings],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'registrations',
      as: :user_registration do
        get :cancel
        get "/payment/edit", as: :edit_payment_settings, to: "registrations#edit_payment_settings"
        get "/twitter_redirect", as: :twitter_redirect, to: "registrations#twitter_redirect"
      end
  end

  root to: "proposals#index"

  resources :users, only: [:index, :destroy] do
    get :watchers
    get :watching
    put :follow
    put :unfollow

    put :impersonate

    resources :characters, controller: "users/characters"
    resources :questions, controller: "users/questions", only: [:create, :update]
    resources :reports, controller: "users/reports", only: [:create]
    resources :wishes, controller: "users/wishes", only: [:create, :destroy]
    resource :profile, controller: "users/profiles", only: [:edit, :update]
    resources :assets, controller: "users/assets", only: [:index, :create, :update, :destroy]
    resources :musics, controller: "users/musics", only: [:create, :update, :destroy]
    get "/pictures", to: "users/assets#index"
  end

  resources :artists, only: [] do
    resources :proposals, only: [:new, :create, :edit, :update, :destroy], controller: "artists/proposals" do
      get :duplicate
    end

    resources :quotations, only: [:new, :create, :index, :edit, :update, :destroy], controller: "artists/quotations" do
      put :publish
      put :unpublish
    end
  end

  resources :commissioners, only: [] do
    resources :quotations, only: [:index], controller: "commissioners/quotations" do
      put :publish
      put :unpublish
    end
  end

  resources :proposals, only: [:index, :show] do
    resources :quotations, only: [:new, :create, :edit, :update, :destroy], controller: "proposals/quotations"

    put :activate
    put :deactivate
  end

  resources :quotations, only: [:show] do
    put :accept
    put :refuse
    put :cancel_approval
    put :cancel_refusal
    put :paid
    put :finish

    put :rate_commissioner
    put :rate_artist

    resources :invoices, controller: "quotations/invoices" do
      put :paid
      put :cancel_paid

      get :paypal_redirect
    end
  end

  resources :quotation_comments, only: [:create]
  resources :characters, only: [:show] do
    put :activate
    put :deactivate
  end

  resources :messages, only: [:index, :create]

  resources :feedbacks, only: [:create]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index, :show] do
    resource :comments, only: [:create], controller: "announcements/comments"
  end

  put "notifications/mark_all_as_read", to: "notifications#mark_all_as_read"

  get "/opensearch.xml" => "proposals#opensearch", as: "opensearch"

  get "/:user_id" => "users/profiles#show", as: "profile"

  get '/s3/sign', to: "s3#sign"

  # legacy
  get "/users/:user_id/profile", to: redirect('/%{user_id}')
  get "/:user_id/characters", to: redirect('/%{user_id}')
  get "/artists/:user_id/proposals", to: redirect('/%{user_id}')
end

app/views/shared/_avatar.html.haml
- if defined?(with_status) && with_status
  %img{alt: user.name, class: "circle responsive-img avatar with-status #{user_class(user)} tooltipped", src: user.profile.avatar_url(:avatar), data: { tooltip: t(".#{user_class(user)}") }}
- else
  %img{alt: user.name, class: "circle responsive-img avatar", src: user.profile.avatar_url(:avatar)}

app/views/shared/_card_filler.html.haml
- ((3 - count) % 3).times do
  .card-filler.col.l4.hide-on-med-and-down{style: "min-height: #{height}px"}
    .card

app/views/shared/_illustration.html.haml
.card.z-depth-05{itemscope: true, itemtype: "http://schema.org/Painting", itemid: user_asset_url(user_id: asset.user.slug, id: asset.id)}
  %meta{itemprop: "thumbnailUrl", content: asset.file_url(:thumbnail)}
  %meta{itemprop: "genre", content: "Illustration"}
  %div{:style => "background-image: url('#{asset.file_url(:thumbnail)}')", class: "card-image card-cover top-card-image #{(asset.is_adult_content && 'nsfw')}"}
    .card-title.card-title-onbright.center-align.asset-description.ellipsis
      %em{itemprop: "description"}= (asset.description.present? ? asset.description : t('.no_description'))
    / That the worst thing I have ever done
    - 5.times do
      %img.materialboxed{:src => "#{asset.file_url}", :data => { caption: (asset.description.present? ? asset.description : t('.no_description')) } }

app/views/shared/_illustration_picker.html.haml
.col.s12.m6.l4
  .card.z-depth-05
    .banner-selector
      - if banner
        = f.radio_button :banner_id, pf.object.asset_id
        = f.label([:banner_id, pf.object.asset_id].join("_")) { "" }
    .card-image.card-cover.top-card-image{"data-check" => "asset-#{pf.object.asset.id}", :style => "background-image: url('#{pf.object.asset.file_url(:thumbnail)}')"}
      .card-title.card-title-onbright.center-align.asset-description{"data-check" => "asset-#{pf.object.asset.id}"}
        %em.ellipsis{"data-check" => "asset-#{pf.object.asset.id}"}
          = (pf.object.asset.description.present? ? pf.object.asset.description : t('.no_description'))
    .card-action.center-align.no-border.no-bottom.empty-label
      = pf.hidden_field :id, value: pf.object.id
      = pf.hidden_field :asset_id, value: pf.object.asset_id
      = pf.check_box :_destroy, { id: "asset-#{pf.object.asset.id}", checked: f.object.assets.include?(pf.object.asset) }, 'f', 't'
      = pf.label("asset-#{pf.object.asset.id}", "data-check" => "asset-#{pf.object.asset.id}") { "" }

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li.hide-on-large-only
    .userView
      %img.background{src: image_url("gplaypattern.png")}
      = link_to profile_path(user_id: current_user.slug) do
        %img.circle{src: current_user.profile.avatar_url(:avatar)}
      = link_to profile_path(user_id: current_user.slug), class: 'name' do
        = current_user.name
      = link_to profile_path(user_id: current_user.slug), class: 'email' do
        = current_user.email

  %li{:class => "#{is_active_link?(notifications_path) && 'active'} #{notifications.none? && 'disabled'} hide-on-large-only"}
    = link_to notifications_path, class: "notifications-link" do
      - if unread_notifications.any?
        = t('.unread_notifications', { count: unread_notifications.count })
        %i.material-icons.right notifications
      - else
        = t('.no_notification')
        %i.material-icons.right notifications_none
  %li.hide-on-large-only
    .divider

  %li{:class => "#{(is_active_link?(proposals_path) || is_active_link?(root_path, :exact)) && 'active'}"}
    = link_to t('.proposals'), root_path

  %li{:class => "#{is_active_link?(commissioner_quotations_path(commissioner_id: current_user.slug)) && 'active'}  #{quotations_as_commissioner.none? && 'disabled'}"}
    = link_to t('.my_quotations_as_commissioner'), commissioner_quotations_path(commissioner_id: current_user.slug)

  %li{:class => "#{is_active_link?(artist_quotations_path(artist_id: current_user.slug)) && 'active'} #{quotations_as_artist.none? && 'disabled'}"}
    = link_to t('.my_quotations_as_artist'), artist_quotations_path(artist_id: current_user.slug)

  %li{:class => is_active_link?(user_assets_path(user_id: current_user.slug)) && 'active'}
    = link_to t('.gallery'), user_assets_path(user_id: current_user.slug)

  %li{:class => "#{is_active_link?(messages_path) && 'active'} #{my_messages.none? && 'disabled'}"}
    = link_to messages_path do
      = t('.my_messages')
      - if unread_messages.count > 0
        %span.message-count.blue= unread_messages.count

  %li{:class => "#{is_active_link?(notifications_path) && 'active'} hide-on-med-and-down notifications"}
    = link_to notifications_path, class: "notifications-link" do
      - if unread_notifications.any?
        %i.material-icons notifications
        %span.notification-count= unread_notifications.count
      - else
        %i.material-icons notifications_none
        %span.notification-count

  %li{:class => "hide-on-med-and-down #{is_on_profile? && 'active'}"}
    = link_to profile_path(user_id: current_user.slug) do
      = render partial: "shared/avatar", locals: { user: current_user }

  %li.hide-on-large-only
    .divider
  - ['terms-of-service', 'acceptable-content-policy', 'about'].each do |page|
    %li.hide-on-large-only
      = link_to t("pages.titles.#{page}"), page_path(page)
  %li.hide-on-large-only
    = link_to t('.sign_out'), destroy_user_session_path, :method => :delete

- else
  %li{:class => "#{is_active_link?(proposals_path) && 'active'}"}
    = link_to t('.proposals'), proposals_path

  %li{:class => "#{is_active_link?(new_user_registration_path) && 'active'}"}
    = link_to t('.sign_up'), new_user_registration_path

  %li{:class => "#{is_active_link?(new_user_session_path) && 'active'}"}
    = link_to t('.sign_in'), new_user_session_path

app/views/shared/_no_image.html.haml
.col.s12
  %h4= t('.no_assets')
  = raw t('.go_to_assets', { assets_path: user_assets_path(user_id: current_user.id) })