config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, skip: :registrations, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider', to: "omniauth_callbacks#%{provider}", as: :user_omniauth_authorize

    resource :registration,
      only: [:new, :create, :edit, :update, :edit_payment_settings],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'registrations',
      as: :user_registration do
        get :cancel
        get "/payment/edit", as: :edit_payment_settings, to: "registrations#edit_payment_settings"
        get "/twitter_redirect", as: :twitter_redirect, to: "registrations#twitter_redirect"
      end
  end

  root to: "proposals#index"

  resources :users, only: [:index, :destroy] do
    get :watchers
    get :watching
    put :follow
    put :unfollow

    put :impersonate

    resources :characters, controller: "users/characters"
    resources :questions, controller: "users/questions", only: [:create, :update]
    resources :reports, controller: "users/reports", only: [:create]
    resources :wishes, controller: "users/wishes", only: [:create, :destroy]
    resource :profile, controller: "users/profiles", only: [:edit, :update]
    resources :assets, controller: "users/assets", only: [:index, :create, :update, :destroy]
    resources :musics, controller: "users/musics", only: [:create, :update, :destroy]
    get "/pictures", to: "users/assets#index"
  end

  resources :artists, only: [] do
    resources :proposals, only: [:new, :create, :edit, :update, :destroy], controller: "artists/proposals" do
      get :duplicate
    end

    resources :quotations, only: [:new, :create, :index, :edit, :update, :destroy], controller: "artists/quotations" do
      put :publish
      put :unpublish
    end
  end

  resources :commissioners, only: [] do
    resources :quotations, only: [:index], controller: "commissioners/quotations" do
      put :publish
      put :unpublish
    end
  end

  resources :proposals, only: [:index, :show] do
    resources :quotations, only: [:new, :create, :edit, :update, :destroy], controller: "proposals/quotations"

    put :activate
    put :deactivate
  end

  resources :quotations, only: [:show] do
    put :accept
    put :refuse
    put :cancel_approval
    put :cancel_refusal
    put :paid
    put :finish

    put :rate_commissioner
    put :rate_artist

    resources :invoices, controller: "quotations/invoices" do
      put :paid
      put :cancel_paid

      get :paypal_redirect
    end
  end

  resources :quotation_comments, only: [:create]
  resources :characters, only: [:show] do
    put :activate
    put :deactivate
  end

  resources :messages, only: [:index, :create]

  resources :feedbacks, only: [:create]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index, :show] do
    resource :comments, only: [:create], controller: "announcements/comments"
  end

  put "notifications/mark_all_as_read", to: "notifications#mark_all_as_read"

  get "/opensearch.xml" => "proposals#opensearch", as: "opensearch"

  get "/:user_id" => "users/profiles#show", as: "profile"

  get '/s3/sign', to: "s3#sign"

  # legacy
  get "/users/:user_id/profile", to: redirect('/%{user_id}')
  get "/:user_id/characters", to: redirect('/%{user_id}')
  get "/artists/:user_id/proposals", to: redirect('/%{user_id}')
end

app/controllers/artists/quotations_controller.rb
class Artists::QuotationsController < ApplicationController

  include SlugRedirectable

  before_action :authenticate_user!, except: [:index]
  before_action :set_artist, only: [:new, :create, :index, :edit, :update]
  before_action :set_quotation, only: [:edit, :update, :destroy, :publish, :unpublish]

  def index
    @quotations = QuotationPolicy::Scope.new(current_user, @artist.quotations_as_artist).resolve_for_artist
      .order(:created_at)
      .includes({ :proposal => [ :delay ] }, :commissioner, :assets)
      .filter(params.permit(:state))
      .page(page)
      .per(per)

    authorize @quotations
  end

  def new
    @quotation = Quotation.new(commissioner: current_user, artist: @artist)
    authorize @quotation
  end

  def create
    @quotation = Quotation.new(strong_params(Quotation.new))
    authorize @quotation

    if @quotation.save
      if params[:publish]
        publish!
        flash[:notice] = I18n.t("artists.quotations.publish.success")
      else
        flash[:notice] = I18n.t("artists.quotations.create.success")
      end

      redirect_to commissioner_quotations_url(commissioner_id: @quotation.commissioner.slug)
    else
      render 'new'
    end
  end

  def update
    @quotation.assign_attributes(strong_params(@quotation))
    authorize @quotation

    if @quotation.save
      if params[:publish]
        publish!
        flash[:notice] = I18n.t("artists.quotations.publish.success")
      else
        flash[:notice] = I18n.t("artists.quotations.create.success")
      end

      redirect_to commissioner_quotations_path(commissioner_id: @quotation.commissioner.slug)
    else
      render 'edit'
    end
  end

  def destroy
    authorize @quotation
    @quotation.destroy

    flash[:notice] = I18n.t("quotations.destroy.success")

    redirect_to commissioner_quotations_path(commissioner_id: @quotation.commissioner.slug)
  end

  def publish
    authorize @quotation, :publish_for_artist?

    @quotation.update(public_for_artist: true)

    head :no_content
  end

  def unpublish
    authorize @quotation, :unpublish_for_artist?

    @quotation.update(public_for_artist: false)

    head :no_content
  end

  protected

  def publish!
    @quotation.publish!
    @quotation.create_activity key: "quotation.publish", owner: current_user, recipient: @quotation.artist

     if @quotation.artist.allow_quotation_created_notification
       NotificationMailer.quotation_created(@quotation).deliver_later
     end
  end

  def set_artist
    @artist = User.find(params[:artist_id])
    redirect_if_new_slug_for(@artist, :artist_id)
  end

  def set_quotation
    @quotation = Quotation.find(params[:id] || params[:quotation_id])
  end
end

app/controllers/commissioners/quotations_controller.rb
class Commissioners::QuotationsController < ApplicationController

  include SlugRedirectable

  before_action :authenticate_user!, except: [:index]
  before_action :set_commisionner
  before_action :set_quotation, only: [:publish, :unpublish]

  def index
    @quotations = QuotationPolicy::Scope.new(current_user, @commissioner.quotations_as_commissioner).resolve_for_commissioner
      .order(:created_at)
      .includes(:artist, :proposal, :commissioner, :assets)
      .filter(params.permit(:state))
      .page(page)
      .per(per)

    authorize @quotations

    respond_to do |format|
      format.html
    end
  end

  def publish
    authorize @quotation, :publish_for_commissioner?

    @quotation.update(public_for_commissioner: true)

    head :no_content
  end

  def unpublish
    authorize @quotation, :unpublish_for_commissioner?

    @quotation.update(public_for_commissioner: false)

    head :no_content
  end

  protected

  def set_commisionner
    @commissioner = User.find(params[:commissioner_id])
    redirect_if_new_slug_for(@commissioner, :commissioner_id)
  end

  def set_quotation
    @quotation = Quotation.find(params[:id] || params[:quotation_id])
  end
end

app/controllers/proposals/quotations_controller.rb
class Proposals::QuotationsController < ApplicationController

  include SlugRedirectable

  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_proposal, only: [:new, :create, :edit, :update]
  before_action :set_quotation, only: [:edit, :update, :destroy]

  def new
    @quotation = Quotation.new(proposal: @proposal, commissioner: current_user, artist: @proposal.artist)
    authorize @quotation
  end

  def create
    @quotation = Quotation.new(strong_params(Quotation.new))
    authorize @quotation

    if @quotation.save
      if params[:publish]
        publish!
        flash[:notice] = I18n.t("proposals.quotations.publish.success")
      else
        flash[:notice] = I18n.t("proposals.quotations.create.success")
      end

      redirect_to commissioner_quotations_url(commissioner_id: @quotation.commissioner.slug)
    else
      render 'new'
    end
  end

  def edit
    authorize @quotation
  end

  def update
    @quotation.assign_attributes(strong_params(@quotation))
    authorize @quotation

    if @quotation.save
      if params[:publish]
        publish!
        flash[:notice] = I18n.t("proposals.quotations.publish.success")
      else
        flash[:notice] = I18n.t("proposals.quotations.create.success")
      end

      redirect_to commissioner_quotations_path(commissioner_id: @quotation.commissioner.slug)
    else
      render 'edit'
    end
  end

  def destroy
    authorize @quotation
    @quotation.destroy

    flash[:notice] = I18n.t("quotations.destroy.success")

    redirect_to commissioner_quotations_path(commissioner_id: @quotation.commissioner.slug)
  end

  protected

  def publish!
    @quotation.publish!
    @quotation.create_activity key: "quotation.publish", owner: current_user, recipient: @quotation.artist

     if @quotation.artist.allow_quotation_created_notification
       NotificationMailer.quotation_created(@quotation).deliver_later
     end
  end

  def set_proposal
    @proposal = Proposal.find(params[:proposal_id])

    redirect_if_new_slug_for(@proposal, :proposal_id)
  end

  def set_quotation
    @quotation = Quotation.find(params[:id])
  end
end

app/controllers/quotations/invoices_controller.rb
class Quotations::InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoice, only: [:paid, :cancel_paid, :paypal_redirect]

  def create
    @invoice = Invoice.new(strong_params(Invoice.new))

    authorize @invoice

    if @invoice.save
      respond_to do |format|
        format.html {
          flash[:notice] = I18n.t("artists.invoices.create.success")

          redirect_back fallback_location: quotation_url(id: @invoice.quotation.id)

        }
        format.json {
          render json: { id: @invoice.id, url: quotation_invoice_url(quotation_id: @invoice.quotation.id, id: @invoice.encrypted_id, format: :pdf) }
        }
      end
    else
      render 'new'
    end
  end

  def show
    @invoice = Invoice.find(Encryptor.decrypt(params[:id]))

    @artist = @invoice.quotation.artist
    @commissioner = @invoice.quotation.commissioner

    respond_to do |format|
      format.pdf do
        render({
            pdf: "invoice_#{@invoice.invoice_reference}_#{@commissioner.name.parameterize.underscore}",
            template: "quotations/invoices/show",
            layout: false,
            encoding: "UTF-8",
            page_size: "A4",
            show_as_html: params.key?('debug')
          })
        end
      end
    end

    def paid
      transition 'paid'

      if @invoice.quotation.artist.allow_quotation_invoice_paid_notification
        NotificationMailer.invoice_paid(@invoice).deliver_later
      end
    end

    def cancel_paid
      transition 'cancel_paid'

      if @invoice.quotation.artist.allow_quotation_invoice_cancel_paid_notification
        NotificationMailer.invoice_cancelled_paid(@invoice).deliver_later
      end
    end

    def paypal_redirect
      paid

      if @invoice.quotation.waiting_payment?
        @invoice.quotation.paid!
        @invoice.quotation.create_activity key: "quotation.paid", owner: @invoice.quotation.artist, recipient: @invoice.quotation.commissioner

        if @invoice.quotation.commissioner.allow_quotation_paid_notification
          NotificationMailer.quotation_paid(@invoice.quotation).deliver_later
        end
      end
    end

    protected

    def transition(event)
      authorize @invoice
      @invoice.send("#{event}!")
      @invoice.create_activity key: "invoice.#{event}", owner: current_user, recipient: @invoice.quotation.artist

      flash[:notice] = I18n.t("invoices.#{event}.success")

      redirect_to quotation_url(@invoice.quotation)
    end

    def set_invoice
      @invoice = Invoice.find(params[:id] || params[:invoice_id])
    end
  end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quotation, only: [:show, :accept, :cancel_approval, :refuse, :paid, :finish, :rate_artist, :rate_commissioner]
  before_action :get_quotation_assets, only: [:show]

  def show
    authorize @quotation

    PublicActivity::Activity.mark_as_read!(PublicActivity::Activity.where(trackable: @quotation).to_a, for: current_user)
    PublicActivity::Activity.mark_as_read!(PublicActivity::Activity.where(trackable: @quotation.comments).to_a, for: current_user)
  end

  def accept
    transition('accept')

    if @quotation.commissioner.allow_quotation_accepted_notification
      NotificationMailer.quotation_accepted(@quotation).deliver_later
    end
  end

  def refuse
    transition('refuse')
    @quotation.update(params.require(:quotation).permit(:refuse_reason, :refuse_comment))

    if @quotation.commissioner.allow_quotation_refused_notification
      NotificationMailer.quotation_refused(@quotation).deliver_later
    end
  end

  def cancel_approval
    transition('cancel_approval')
    @quotation.update(refuse_reason: nil, refuse_comment: nil)

    if @quotation.commissioner.allow_quotation_cancelled_notification
      NotificationMailer.quotation_cancelled(@quotation).deliver_later
    end
  end

  def paid
    transition('paid')

    if @quotation.commissioner.allow_quotation_paid_notification
      NotificationMailer.quotation_paid(@quotation).deliver_later
    end
  end

  def finish
    transition('finish')

    if @quotation.commissioner.allow_quotation_done_notification
      NotificationMailer.quotation_done(@quotation).deliver_later
    end
  end

  def rate_commissioner
    authorize @quotation
    @quotation.update(commissioner_rating: params[:rating])

    flash[:notice] = I18n.t("quotations.rate_commissioner.success")
    redirect_back fallback_location: quotation_url(@quotation)
  end

  def rate_artist
    authorize @quotation
    @quotation.update(artist_rating: params[:rating])

    flash[:notice] = I18n.t("quotations.rate_artist.success")
    redirect_back fallback_location: quotation_url(@quotation)
  end

  protected

  def transition(event)
    authorize @quotation
    @quotation.send("#{event}!")
    @quotation.create_activity key: "quotation.#{event}", owner: current_user, recipient: @quotation.commissioner

    flash[:notice] = I18n.t("quotations.#{event}.success")

    redirect_to quotation_url(@quotation)
  end

  def get_quotation_assets
    @quotation_assets = @quotation.assets.by_reversed_date
  end

  def set_quotation
    @quotation = Quotation.includes(comments: [:attachments]).find(params[:id] || params[:quotation_id])
  end

end

app/helpers/artists/quotations_helper.rb
module Artists::QuotationsHelper
  def artist_quotation_count_by_state(user, state)
    QuotationPolicy::Scope.new(current_user, user.quotations_as_artist).resolve_for_artist.filter({state: state}).count
  end
end

app/helpers/commissioners/quotation_helper.rb
module Commissioners::QuotationHelper
  def commissioner_quotation_count_by_state(user, state)
    QuotationPolicy::Scope.new(current_user, user.quotations_as_commissioner).resolve_for_commissioner.filter({state: state}).count
  end
end

app/helpers/proposals/quotations_helper.rb
module Proposals::QuotationsHelper
end

app/helpers/quotations/invoices_helper.rb
module Quotations::InvoicesHelper
  def build_paypal_me_link(invoice)
    _, username, price, currency_uid = URI.parse(invoice.invoicing_paypal_address).path.match(/\/([^\/]*)\/?([0-9]*)?(.*)?/).to_a

    price = invoice.price if price.blank?
    currency_uid = invoice.currency_uid if currency_uid.blank?

    "https://paypal.me/#{username}/#{price}#{currency_uid}"
  end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
  def addition_illustrations
    pundit_policy_scope(current_user.assets).order(created_at: :desc) - current_user.characters_assets
  end
end

app/views/quotations/_actions.html.haml
- if quotation.artist == current_user && params[:controller] == "artists/quotations"
  = render partial: "quotations/artist_actions", locals: { quotation: quotation }
- elsif quotation.commissioner == current_user && params[:controller] == "commissioners/quotations"
  = render partial: "quotations/commissioner_actions", locals: { quotation: quotation }

app/views/quotations/_artist_actions.html.haml
.card-action.flex-align
  - if (policy(quotation).publish_for_artist? || policy(quotation).unpublish_for_artist?)
    .visibility-switch{ data: { 'quotation-id' => quotation.id, 'role' => 'artist', 'checked-message': t('.request_public_feedback'), 'unchecked-message': t('.request_private_feedback') }}
      %input.filled-in{type: "checkbox", id: "quotation-visibility-#{quotation.id}", checked: quotation.public_for_artist? }
      %label{for: "quotation-visibility-#{quotation.id}"}= t(".is_public")
  - else
    %div

  = link_to t('.details'), quotation_path(id: quotation.id), class: 'blue-text darken-4'

app/views/quotations/_commissioner_actions.html.haml
.card-action.flex-align
  - if policy(quotation).publish_for_commissioner? || policy(quotation).unpublish_for_commissioner?
    .visibility-switch{ data: { 'quotation-id' => quotation.id, 'role' => 'artist', 'checked-message': t('.order_public_feedback'), 'unchecked-message': t('.order_private_feedback') }}
      %input.filled-in{type: "checkbox", id: "quotation-visibility-#{quotation.id}", checked: quotation.public_for_commissioner? }
      %label{for: "quotation-visibility-#{quotation.id}"}= t(".is_public")

  - else
    %div
  - if policy(quotation).edit?
    - if quotation.proposal.present?
      = link_to t('.edit'), edit_proposal_quotation_path(proposal_id: quotation.proposal.slug, id: quotation.id), class: 'blue-text darken-4'
    - else
      = link_to t('.edit'), edit_artist_quotation_path(artist_id: quotation.artist.slug, id: quotation.id), class: 'blue-text darken-4'
  - else
    = link_to t('.details'), quotation_path(id: quotation.id), class: 'blue-text darken-4'

app/views/quotations/_invoice.html.haml
.card.blue-grey.darken-1.inline-invoice
  .card-content.white-text
    .card-title
      %strong= t(".invoice", reference: invoice.invoice_reference)
    .row
      .col.s12.m6.l4
        %h5= t(".price")
        = invoice.price
      .col.s12.m6.l4
        %h5= t(".currency")
        = invoice.currency_uid
      - if invoice.due_date.present?
        .col.s12.m6.l4
          %h5= t(".due_date")
          = invoice.due_date.strftime("%F")
      - if invoice.invoicing_paypal_address.present?
        .col.s12
          %h5= t(".invoicing_paypal_address")
          - if ["http", "https"].include?(URI.parse(invoice.invoicing_paypal_address).scheme)
            %span.blue-text.text-lighten-2= invoice.invoicing_paypal_address
            = link_to t(".go_to_paypal"), build_paypal_me_link(invoice), class: "btn z-depth-0 blue-grey darken-3 payment-btn-form", target: "_blank", rel: "noopener"
          - else
            = invoice.invoicing_paypal_address
            - if policy(invoice).paid? && invoice.quotation.artist.has_business_paypal?
              %form{action: "https://www.paypal.com/cgi-bin/webscr", method: "POST", class: "payment-btn-form"}
                %input{type: "hidden", NAME: "cmd", value: "_xclick"}
                %input{type: "hidden", NAME: "business",value: invoice.invoicing_paypal_address}
                - if invoice.quotation.proposal.present?
                  %input{type: "hidden", NAME: "item_name", value: t("artists.proposals.proposal.style", { category: invoice.quotation.proposal.category.name, style: invoice.quotation.proposal.style.name })}
                - else
                  %input{type: "hidden", NAME: "item_name", value: t(".custom_commission") }

                %input{type: "hidden", NAME: "item_number", value: "1"}
                %input{type: "hidden", NAME: "amount", value: invoice.price}
                %input{type: "hidden", name: "return", value: quotation_invoice_paypal_redirect_url(quotation_id: invoice.quotation.id, invoice_id: invoice.id)}
                %input{type: "hidden", NAME: "currency_code", value: invoice.currency_uid}
                %button.btn.z-depth-0.blue-grey.darken-3
                  = t(".go_to_paypal")

      - if invoice.quotation.commissioner.billing_paypal_address.present?
        .col.s12
          %h5= t(".billing_paypal_address")
          = invoice.quotation.commissioner.billing_paypal_address

    - if invoice.additional_informations.present?
      %blockquote= format_text(invoice.additional_informations)
  - if invoice.quotation.commissioner == current_user
    .card-action.flex-align
      = link_to quotation_invoice_url(quotation_id: invoice.quotation.id, id: invoice.encrypted_id, format: :pdf), class: 'btn-flat white-text ellipsis' do
        %i.material-icons.left.white-text file_download
        = t(".download_full_invoice")
      - if policy(invoice).paid?
        = button_to quotation_invoice_paid_path(quotation_id: invoice.quotation.id, invoice_id: invoice.id), method: :put, class: "btn z-depth-0 blue lighten-1" do
          %i.material-icons.right.white-text attach_money
          = t(".mark_as_paid")
      - if policy(invoice).cancel_paid?
        = button_to quotation_invoice_cancel_paid_path(quotation_id: invoice.quotation.id, invoice_id: invoice.id), method: :put, class: "btn z-depth-0 red lighten-1" do
          %i.material-icons.right.white-text money_off
          = t(".cancel_paid")

  - else
    .card-action.right-align
      = link_to quotation_invoice_url(quotation_id: invoice.quotation.id, id: invoice.encrypted_id, format: :pdf), class: 'btn-flat white-text ellipsis' do
        %i.material-icons.right.white-text file_download
        = t(".download_full_invoice")

app/views/quotations/show.html.haml
- content_for :page_title do
  - if @quotation.proposal.present?
    = render partial: 'quotations/proposal_quotation_page_title', locals: { quotation: @quotation }
  - else
    = render partial: 'quotations/custom_quotation_page_title', locals: { quotation: @quotation }

.container
  .row
    .col.s12.l10.offset-l1
      .card.page-card-with-image

        - if @quotation.proposal.present?
          = render partial: 'quotations/proposal_quotation_card_title', locals: { quotation: @quotation }
        - else
          = render partial: 'quotations/custom_quotation_card_title', locals: { quotation: @quotation }

        .card-content
          - if @quotation.state == "done"
            .row
              .col.s12
                - if @quotation.artist == current_user
                  .rating
                    %h5= raw t(".commissioner_rating.title", { commissioner_name: h(@quotation.commissioner.name) })
                    %ul
                      - Quotation::SENTIMENTS.each do |sentiment|
                        %li
                          = link_to quotation_rate_commissioner_path(@quotation, rating: sentiment), method: :put, class: (sentiment.to_s == @quotation.commissioner_rating && 'current') do
                            %i.material-icons= "sentiment_#{sentiment}"
                          .explanation
                            = t(".commissioner_rating.values.#{sentiment}")

                - elsif @quotation.commissioner == current_user
                  .rating
                    %h5= raw t(".artist_rating.title")
                    %ul
                      - Quotation::SENTIMENTS.each do |sentiment|
                        %li
                          = link_to quotation_rate_artist_path(@quotation, rating: sentiment), method: :put, class: (sentiment.to_s == @quotation.artist_rating && 'current') do
                            %i.material-icons= "sentiment_#{sentiment}"
                          .explanation
                            = t(".artist_rating.values.#{sentiment}")
          .row
            .col.s12
              %ul.collection.comments#comments
                - if policy(QuotationComment.new(quotation: @quotation)).create?
                  %li.collection-item
                    .row
                      .col.m2.center-align.hide-on-small-only
                        %img.responsive-img.circle{:alt => "", :src => "#{current_user.profile.avatar_url(:avatar)}"}
                        %br

                      .col.s12.m10
                        = form_for(QuotationComment.new, remote: true) do |f|
                          = f.hidden_field 'quotation_id', value: @quotation.id
                          = f.file_field 'attachment', multiple: true, data: { "attachment-upload" => true, "owner" => current_user.id }

                          = f.text_area 'body', class: "materialize-textarea", placeholder: t('.send_comment')
                          .files-to-upload

                          .flex-align
                            %div.quotation-attachments.attachment-wrapper
                              - if policy(Invoice.new(quotation: @quotation)).create?
                                = link_to '#invoicing-modal', class: "btn z-depth-0 waves-effect waves-light left hide-on-med-and-down" do
                                  %i.material-icons.right attach_money
                                  = t(".attach_invoice")

                                = link_to '#invoicing-modal', class: "btn-floating z-depth-0 waves-effect waves-light left hide-on-large-only" do
                                  %i.material-icons.right attach_money

                              .attachment-upload.left
                                .btn.z-depth-0.waves-effect.waves-light.hide-on-med-and-down{onclick: "$('#quotation_comment_attachment').click()"}
                                  %i.material-icons.right attach_file
                                  = t(".attach_files")
                                .btn-floating.z-depth-0.waves-effect.waves-light.hide-on-large-only{onclick: "$('#quotation_comment_attachment').click()"}
                                  %i.material-icons.right attach_file

                                .preloader-wrapper.big.active
                                  .spinner-layer.spinner-blue-only
                                    .circle-clipper.left
                                      .circle
                                    .gap-patch
                                      .circle
                                    .circle-clipper.right
                                      .circle
                            = f.button class: 'waves-effect waves-light btn-flat' do
                              = t('.submit_comment')

                - @quotation.comments.each do |comment|
                  %li.collection-item.conversation
                    .row.row-no-bottom-margin
                      .col.s3.m2.center-align
                        = link_to profile_path(comment.sender) do
                          %img.responsive-img.circle{:src => "#{comment.sender.profile.avatar_url(:avatar)}"}
                        %br/
                        %span.ago= t(".ago", { time: time_ago_in_words(comment.created_at) })
                      .col.s9.m10
                        = render partial: "quotations/comment", locals: { comment: comment }

              .divider

          %h4.top= t('.description')

          %blockquote
            %p= format_text(@quotation.description)
          - if @quotation_assets.any?
            %h4= t('.assets')
            .row
              - @quotation_assets.each do |asset|
                .col.s12.m6.l4
                  = render partial: 'shared/illustration', locals: { asset: asset }

          - if @quotation.characters.any?

            %h4.top= t('.characters', { count: @quotation.characters.count })

            - @quotation.characters.each do |character|
              .card.horizontal.character.z-depth-05
                .card-image{:style => "background-image: url('#{character.illustration_for(current_user, :thumbnail)}')"}
                .card-stacked
                  .card-content
                    %h4.ellipsis= link_to character.name, character
                    = character.species
                    %h5= t('.description')
                    = format_text(truncate(character.description, { length: 200, separator: ' '}) { link_to " #{t('.read_more')}", character, class: 'blue-text darken-4' } )

                  .card-action.right-align
                    = link_to t('.character_details'), character, class: 'blue-text darken-4'

        - if current_user == @quotation.artist && @quotation.state != 'done'
          .card-action.right-align
            - case @quotation.state
            - when 'waiting_approval'
              = link_to t("quotations.events.refuse"), '#refuse-modal', class: 'btn-flat red-text modal-trigger'
              = button_to send("quotation_accept_path", quotation_id: @quotation.id), { method: :put, class: 'btn z-depth-0' } do
                = t("quotations.events.accept")
            - when 'waiting_payment'
              = button_to t("quotations.events.cancel_approval"), send("quotation_cancel_approval_path", quotation_id: @quotation.id), { method: :put, class: 'btn-flat' }
              = button_to t("quotations.events.paid"), send("quotation_paid_path", quotation_id: @quotation.id), { method: :put, class: 'btn z-depth-0' }
            - when 'paid'
              = button_to t("quotations.events.finish"), send("quotation_finish_path", quotation_id: @quotation.id), { method: :put, class: 'btn z-depth-0' }
            - when 'refused'
              = button_to t("quotations.events.cancel_approval"), send("quotation_cancel_approval_path", quotation_id: @quotation.id), { method: :put, class: 'btn-flat' }
        - else
          .empty-card-action
= render partial: "quotations/refuse_modal", locals: { quotation: @quotation }

- if policy(Invoice.new(quotation: @quotation)).create?
  = render partial: "quotations/invoicing_modal", locals: { quotation: @quotation }